apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SatishThapak/kubernetes_learnings.git
    targetRevision: HEAD
    path: nginx-deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-web
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
